"""empty message

Revision ID: 0418f8bc5bfc
Revises: 3ef7dc71c390
Create Date: 2025-11-04 16:53:36.754015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0418f8bc5bfc'
down_revision = '3ef7dc71c390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotacao_cultura',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Double(precision=100), nullable=False),
    sa.Column('idCultura', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['idCultura'], ['cultura.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cotacao_cultura')
    # ### end Alembic commands ###
