"""empty message

Revision ID: 3ef7dc71c390
Revises: 81a03045c16d
Create Date: 2025-11-04 16:34:20.300009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef7dc71c390'
down_revision = '81a03045c16d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maquina',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('maquina', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('maquina')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maquina')
    # ### end Alembic commands ###
