"""empty message

Revision ID: 4402f67e48e7
Revises: 
Create Date: 2025-12-05 21:59:59.482411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4402f67e48e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cultura',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('maquinario',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('maquina', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('maquina')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=355), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('cotacao_cultura',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('precoAtual', sa.Double(precision=100), nullable=False),
    sa.Column('precoAlvoVenda', sa.Double(precision=100), nullable=False),
    sa.Column('variacao24h', sa.Double(precision=100), nullable=False),
    sa.Column('idCultura', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['idCultura'], ['cultura.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('funcionario',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('idCultura', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['idCultura'], ['cultura.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('horas_funcionario',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('horas', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('idFuncionario', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['idFuncionario'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('uso_maquinario',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('idMaquinario', sa.String(length=50), nullable=False),
    sa.Column('idFuncionario', sa.String(length=50), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idFuncionario'], ['funcionario.id'], ),
    sa.ForeignKeyConstraint(['idMaquinario'], ['maquinario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uso_maquinario')
    op.drop_table('horas_funcionario')
    op.drop_table('funcionario')
    op.drop_table('cotacao_cultura')
    op.drop_table('user')
    op.drop_table('maquinario')
    op.drop_table('cultura')
    # ### end Alembic commands ###
