"""empty message

Revision ID: 848a3c6d5215
Revises: 0418f8bc5bfc
Create Date: 2025-11-04 17:13:57.320363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848a3c6d5215'
down_revision = '0418f8bc5bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcionario',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('idCultura', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['idCultura'], ['cultura.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funcionario')
    # ### end Alembic commands ###
