"""empty message

Revision ID: cda200513ddf
Revises: 848a3c6d5215
Create Date: 2025-11-04 17:45:07.757040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda200513ddf'
down_revision = '848a3c6d5215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horas_funcionario',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('horas', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('idFuncionario', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['idFuncionario'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horas_funcionario')
    # ### end Alembic commands ###
