"""empty message

Revision ID: ee984b964975
Revises: cda200513ddf
Create Date: 2025-11-04 18:52:09.453822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee984b964975'
down_revision = 'cda200513ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maquinario',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('maquina', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('maquina')
    )
    op.create_table('uso_maquinario',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('idCultura', sa.String(length=50), nullable=False),
    sa.Column('idMaquinario', sa.String(length=50), nullable=False),
    sa.Column('tempo_uso', sa.Integer(), nullable=False),
    sa.Column('data_uso', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['idCultura'], ['cultura.id'], ),
    sa.ForeignKeyConstraint(['idMaquinario'], ['maquinario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('maquina')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maquina',
    sa.Column('id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('maquina', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('maquina')
    )
    op.drop_table('uso_maquinario')
    op.drop_table('maquinario')
    # ### end Alembic commands ###
